M48
; DRILL file {KiCad 7.0.10} date Wed Mar 20 10:30:24 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-20T10:30:24+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X107.0Y-26.0
X107.0Y-82.0
X154.0Y-26.0
X154.0Y-82.0
M30
